Project:
    _key: project
    id: project
    creation_time: creation_time
Country:
    _key: country
    id: country
    name: country
User:
    _key: manager
    id: manager
    name: manager
    surname: manager
Experiment:
    batches:
        variables:
            _key: 'Experiment' 
            name: 'Experiment'
Run:
    batches:
        _key: id
        id: id
        name: name
        run_start: batch_start
        run_end: batch_end
        run_date: creation_time
        variables: 
            is_control: 'Control?'
            replicate_number: 'Replicate #'
Fermenter:
    batches:
        variables:
            _key: 'Container Type'
            id: 'Container Type'
            name: 'Container Type'
Medium:
    batches:
        variables:
            _key: 'Base Medium'
            name: 'Base Medium'
Phase: 
    batches:
        phases:
            _key: name
            id: name
            name: name
Event: 
    batches:
        events:
            _key: name  
            id: name
            name: name