Project:
    _key: project
    # id: id
    name: name
    description: description
    progress: progress
    status: status
    deletable: deletable
    editable: editable
    type: type
    creation_time: creation_time
    tags: tags
    modification_time: modification_time
    start: start
    end: end
Country:
    _key: country
    name: country
User:
    _key: manager/username
    name: manager/first_name
    surname: manager/last_name
# Institution:
#     _key: 
#     name:
#     address:
#     email:
#     phone_number:
Batch_cell_culture:
    _key: id
    name: name
    # events: event_names
    # workflow: workflow
Run:
    batches:
        _key: id
        name: name
        description: description
        creation_time: creation_time
        modification_time: modification_time
        batch_start: batch_start
        batch_end: batch_end
        first_timestamp: first_timestamp
        last_timestamp: last_timestamp
        # workflow: workflow/calculator_use_groups/id
        variables: variables 




    