Project:
    _key: project
    id: project
Country:
    _key: country
    id: country
    name: country
User:
    _key: manager/username
    id: manager/username
    name: manager/first_name
    surname: manager/last_name
Run:
    batches:
        id: id
        name: name
        run_date: creation_time
        run_start: batch_start
        run_end: batch_end
        variables: variables 
        phases: phases
        events: events
Phase_event: 
    event_name: event_names 
    batch_phase_name: batch_phase_names 




    