######### TODO: FLIP!!!! #######
Run: 
    id: id 
    culture_type: Culture Type
    sample_id: Sample ID
    replicate_number: 'Replicate #'
    is_control: Control?

Fermenter:
    name: Container Type

Cultivation_condition: 
    #Tº
    temperature_setpoint_celsius: Temperature Setpoint (C)
    
    #pH
    pH_setpoint: pH Setpoint
    ph_control_base_solution: pH Control Base Solution  
    ph_control_acid_solution: pH Control Acid Solution

    # DO: Stirr, Airflow, Oxygenflow
    DO_control_setpoint_percentage: DO Control Setpoint (%) 
    DO_control_cascade_level1: DO Control Cascade Level 1  
    DO_control_cascade_level2: DO Control Cascade Level 2  
    DO_control_cascade_level3: DO Control Cascade Level 3 
    stirrer_speed: Stirrer speed
    maximum_stirring_speed_rpm: Maximum Stirring or Shaking Speed (rpm) 
    minimum_stirring_speed_rpm: Minimum Stirring or Shaking Speed (rpm)
    air_flow: Air flow
    aeration_gas_type: Aeration Gas Type 
    maximum_aeration_slpm: Maximum Aeration (slpm) 
    minimum_aeration_slpm: Minimum Aeration (slpm) 
    oxygen_flow: Oxygen flow
    inlet_air_o2: Inlet air O2
    inlet_air_co2: Inlet air CO2
    

    # Sample/Seed/OD
    seed: Seed
    starting_OD: Starting OD
    final_seed_od: Final Seed OD
    initial_volume: Initial Culture VolumeNone 
    culture_volume_unit: Culture Volume Unit

Process_condition: 
    DO: DO
    ph: pH
    temperature: Temperature
    pressure: Pressure

    # Analytical data - offline
    OD: OD
    ******TODO!!!! 
    residual_compound_amount: [ 
        Residual Acetic acid amount
        Residual Citric acid amount
        Residual D-glucose amount
        Residual Ethanol amount
        Residual Lactate amount
        Residual Pyruvic acid amount
        Residual Succinic acid amount
    ]
    ******
    
    # Volume
    liquid_volume: Liquid volume
    liquid_volume_downscaled: Liquid volume downscaled
    volume_addednone: Volume AddedNone
    volume_unitnone: Volume UnitNone
    volume_to_addnone: Volume to AddNone
    
    # Sampling
    sample_mass: Sample mass
    sample_volume: Sample volume 
    accumulated_sample_volume: Accumulated sample volume

    # Feeding
    acid_volume: Acid volume
    base_volume: Base volume
    base_rate: Base rate
    feed_1_rate_gavimetric: Feed 1 rate gavimetric
    feed_1_rate_volumetric: Feed 1 rate volumetric
    feed_1_volume: Feed 1 volume
    feed_amount: Feed amount

    # Monitored variables for each metabolite (example with acetic acid, but we also have: for substrate(D-glucose), byproducts, primary products, CO2 and O2)
    #Citric Acid, Lactate, Pyruvic acid, Succinic acid, Tryptophan, Melatonin
    Acetic acid formed:
    Acetic acid formed molar:
    Acetic acid formation rate molar:
    Acetic acid lost in sample:
    Residual Acetic acid amount:

    # Biomass
    Biomass amount: biomass_amount
    Biomass concentration: biomass_concentration
    Biomas lost in sample: biomass_lostin_sample

    # Substrate
    D-glucose: d_glucose
    D-glucose lost in sample: d_glucose_lostin_sample

    # O2
    O2 Q: o2_q
    O2 decimal: o2_decimal
    Offgas O2: offgas_o2
    Consumed O2: consumed_o2 # or as OUR?

    # CO2
    CO2 Q: co2_q
    CO2 decimal: co2_decimal
    Formed CO2: formed_co2
    Offgas CO2: offgas_co2

Medium:
    Base Medium: base_medium
    'Feed Medium #1': feed_medium_1 
    'Feed Medium #2': feed_medium_2 

Strain:
    Strain: name

Compounds:
    #Substrate
    D-glucose: d_glucose
    
    #Primary products
    melatonin: melatonin
    tryptophan: tryptophan

    #By-products
    acetic acid: acetic_acid
    caffeine: caffeine
    citric acid: citric_acid
    lactate: lactate
    pyruvic acid: pyruvic acid
    succinic acid: succinic acid

kPI:
    # Biomass
    Biomass amount molar:
    Biomass formation rate: biomass_rate
    Biomass formation rate molar: biomass_molar_rate
    Biomass formed:
    Biomass formed c-molar:
    Biomass formed molar:
    Biomass specific growth rate μ:
    Biomass specific growth rate μ_max in Feed:
    Biomass specific growth rate μ_mean in Feed:
    Biomass specific growth rate μ_min in Feed:
    Biomass yield (S): biomass_yield
    Biomass yield c-molar (S): biomass_c-molar_yield
    Biomass yield molar (S): biomass_molar_yield

    # Respiratory activity measurements
    OTR: OTR
    CTR: CTR
    RQ: RQ
    Consumed O2: OUR # Oxygen Uptake Rate
    Formed CO2: CER # CO2 Evolution Rate or Formed CO2 ???????????

    #CO2
    CO2 accumulated:
    CO2 accumulated downscaled:
    CO2 evolution rate:
    CO2 molar:
    CO2 partial integration:
    CO2 specific evolution rate:
    CO2 yield (S):
    CO2 yield (X):
    CO2 yield c-molar (S):
    
    # Oxygen
    O2 accumulated:
    O2 accumulated downscaled:
    O2 molar:
    O2 partial integration:
    O2 specific uptake rate:
    O2 uptake rate: our
    O2 yield (S):
    O2 yield (X):
    O2 yield c-molar (S):


    # Substrate/Carbon Source
    D: dilution_rate 
    C balance: c_balance
    C balance (using c-mols): c_balance_c_mols
    Elemental C balance with reference to substrate: c_balance_to_substrate
    DoR: dor #degreee of reduction (available electrons per C atom)
    DoR (from yields): yields_dor
    DoR balance: dor_balance

    # Substrate
    D-glucose consumed:
    D-glucose consumed c-molar:
    D-glucose consumed molar:
    D-glucose specific uptake rate:
    D-glucose specific uptake rate_max in Feed:
    D-glucose specific uptake rate_mean in Feed:
    D-glucose specific uptake rate_min in Feed:
    D-glucose uptake rate:
    D-glucose uptake rate molar:
    D-glucose yield (X):
    D-glucose yield c-molar (X):
    D-glucose yield molar (X):

    # Calculated variables for each metabolite (example with acetic acid, but we also have for other byproducts and primary products
    #Citric Acid, Lactate, Pyruvic acid, Succinic acid, Tryptophan, Melatonin
    Acetic acid formed:
    Acetic acid formed c-molar:
    Acetic acid specific formation rate:
    Acetic acid specific formation rate molar:
    Acetic acid yield (S):
    Actic acid yield (X):
    Acetic acid yield c-molar (S):
    Acetic acid yield c-molar (X):
    Acetic acid yield molar (S):
    Acetic acid yield molar (X):
