Run:
    id: id 
    Culture Type: culture_type 
    Seed: seed # needed?
    Sample ID: sample_id # same as: Main Culture ID: main_culture_id 
    Experiment: experiment
    'Replicate #': replicate_number
    Control?: is_control 
    Comments: comments 
    Inducer: inducer 
    Volume Unit_INDUCTION: volume_unit_induction 
    Condition: condition 
    Strain Batch: strain_batch # move to Strain edge attribute (MOVE)
Fermenter:
    Container Type: name
    Container ID (calculated): container_id # same as: Reactor/Plate/Flask Number: reactor_number ????

Operating_condition: # Only scalar and categorical not timeseries? Constant parameters
    SOP: SOP 
    Pressure: pressure
    # DO
    DO Control Setpoint (%): DO_control_setpoint_percentage 
    Starting OD: starting_OD # or in process condition?
    DO Control Cascade Level 1: DO_control_cascade_level1 
    DO Control Cascade Level 2: DO_control_cascade_level2 
    DO Control Cascade Level 3: DO_control_cascade_level3 
    Stirrer speed: stirrer_speed # Level 1
    Maximum Stirring or Shaking Speed (rpm): maximum_stirring_speed_rpm 
    Minimum Stirring or Shaking Speed (rpm): minimum_stirring_speed_rpm
    Air flow: air_flow # Level 2
    Aeration Gas Type: aeration_gas_type 
    Aeration Profile: aeration_profile 
    Maximum Aeration (slpm): maximum_aeration_slpm 
    Minimum Aeration (slpm): minimum_aeration_slpm 
    Oxygen flow: oxygen_flow # Level 3
    Inlet air O2: inlet_air_o2
    Inlet air CO2: inlet_air_co2

Cultivation_condition: # Experimental conditions (categorical or scalar) not timeseries or yes?
    #pH (as environment in Operating condition?)
    pH Setpoint: pH_setpoint
    pH Control Base Solution: ph_control_base_solution 
    Base rate: base_rate
    Base volume: base_volume
    pH Control Acid Solution: ph_control_acid_solution
    Acid volume: acid_volume
    #TºC (in Operating cond?)
    Temperature Setpoint (C): temperature_setpoint_celsius 
    # Sample/Seed (as run attributes or in Strain/Sample/Seed/Starter?)
    Final Seed OD: final_seed_od
    Initial Culture VolumeNone: initial_volume 
    Culture Volume Unit: culture_volume_unit

Process_condition: # Timeseries or lists only? Sample measurements
    OD: OD
    DO: DO
    pH: ph
    Temperature: temperature

    # Volume
    Liquid volume: liquid_volume
    Liquid volume downscaled: liquid_volume_downscaled
    Volume AddedNone: volume_addednone
    Volume UnitNone: volume_unitnone
    Volume to AddNone: volume_to_addnone
    
    # Sampling
    Sample mass: sample_mass
    Sample volume: sample_volume
    Accumulated sample volume: accumulated_sample_volume

    # Feeding
    Feed 1 rate gavimetric: feed_1_rate_gavimetric
    Feed 1 rate volumetric: feed_1_rate_volumetric
    Feed 1 volume: feed_1_volume
    Feed amount: feed_amount

    # Monitored variables for each metabolite (example with acetic acid, but we also have: for substrate(D-glucose), byproducts, primary products, CO2 and O2)
    #Citric Acid, Lactate, Pyruvic acid, Succinic acid, Tryptophan, Melatonin
    Acetic acid formed:
    Acetic acid formed molar:
    Acetic acid formation rate molar:
    Acetic acid lost in sample:
    Residual Acetic acid amount:

    # Biomass
    Biomass amount: biomass_amount
    Biomass concentration: biomass_concentration
    Biomas lost in sample: biomass_lostin_sample

    # Substrate
    D-glucose: d_glucose
    D-glucose lost in sample: d_glucose_lostin_sample

    # O2
    O2 Q: o2_q
    O2 decimal: o2_decimal
    Offgas O2: offgas_o2
    Consumed O2: consumed_o2 # or as OUR?

    # CO2
    CO2 Q: co2_q
    CO2 decimal: co2_decimal
    Formed CO2: formed_co2
    Offgas CO2: offgas_co2

Medium:
    Base Medium: base_medium
    'Feed Medium #1': feed_medium_1 
    'Feed Medium #2': feed_medium_2 

Carbon_source:
    D-glucose: d_glucose
Energy_source:
    D-glucose: d_glucose

Strain:
    Strain: name

Primary_product:
    melatonin: melatonin
    tryptophan: tryptophan

Byproduct:
    acetic acid: acetic_acid
    caffeine: caffeine
    citric acid: citric_acid
    lactate: lactate
    pyruvic acid: pyruvic acid
    succinic acid: succinic acid

Metal_ion:

kPI:
    # Biomass
    Biomass amount molar:
    Biomass formation rate: biomass_rate
    Biomass formation rate molar: biomass_molar_rate
    Biomass formed:
    Biomass formed c-molar:
    Biomass formed molar:
    Biomass specific growth rate μ:
    Biomass specific growth rate μ_max in Feed:
    Biomass specific growth rate μ_mean in Feed:
    Biomass specific growth rate μ_min in Feed:
    Biomass yield (S):
    Biomass yield c-molar (S):
    Biomass yield molar (S): biomass_molar_yield

    # Respiratory activity measurements
    OTR: OTR
    CTR: CTR
    RQ: RQ
    Consumed O2: OUR # Oxygen Uptake Rate
    Formed CO2: CER # CO2 Evolution Rate or Formed CO2 ???????????

    #CO2
    CO2 accumulated:
    CO2 accumulated downscaled:
    CO2 evolution rate:
    CO2 molar:
    CO2 partial integration:
    CO2 specific evolution rate:
    CO2 yield (S):
    CO2 yield (X):
    CO2 yield c-molar (S):
    
    # Oxygen
    O2 accumulated:
    O2 accumulated downscaled:
    O2 molar:
    O2 partial integration:
    O2 specific uptake rate:
    O2 uptake rate: our
    O2 yield (S):
    O2 yield (X):
    O2 yield c-molar (S):


    # Substrate/Carbon Source
    D: dilution_rate 
    C balance: c_balance
    C balance (using c-mols): c_balance_c_mols
    Elemental C balance with reference to substrate: c_balance_to_substrate
    DoR: dor #degreee of reduction (available electrons per C atom)
    DoR (from yields): yields_dor
    DoR balance: dor_balance

    # Substrate
    D-glucose consumed:
    D-glucose consumed c-molar:
    D-glucose consumed molar:
    D-glucose specific uptake rate:
    D-glucose specific uptake rate_max in Feed:
    D-glucose specific uptake rate_mean in Feed:
    D-glucose specific uptake rate_min in Feed:
    D-glucose uptake rate:
    D-glucose uptake rate molar:
    D-glucose yield (X):
    D-glucose yield c-molar (X):
    D-glucose yield molar (X):

    # Calculated variables for each metabolite (example with acetic acid, but we also have for other byproducts and primary products
    #Citric Acid, Lactate, Pyruvic acid, Succinic acid, Tryptophan, Melatonin
    Acetic acid formed:
    Acetic acid formed c-molar:
    Acetic acid specific formation rate:
    Acetic acid specific formation rate molar:
    Acetic acid yield (S):
    Actic acid yield (X):
    Acetic acid yield c-molar (S):
    Acetic acid yield c-molar (X):
    Acetic acid yield molar (S):
    Acetic acid yield molar (X):
